export const EXPANDED_NODE_DEFAULT_WIDTH = 660;
export const EXPANDED_NODE_MIN_WIDTH = 420;
export const EXPANDED_NODE_MIN_HEIGHT = 240;
export const EXPANDED_NODE_MAX_WIDTH = 1600;
export const EXPANDED_NODE_MAX_HEIGHT = 1200;
